

#' @title consthcr conducts the MCDA and returns the TAC multiplier and details
#'
#' @description consthcr enables one to implement constant aspirational catches
#'     for each sau, this can act as a form of status quo approach. All it 
#'     requires is for the hsargs = a vector of nsau aspirational catches. Then,
#'     in the do-MSE function replace 'hcrfun=mcdahcr' with 'hcrfun=consthcr',
#'     'getdata=tasdata' with 'getdata=constdata, and finally, 
#'     'makeouthcr=makeouthcr' with 'makeouthcr=makeoutconst'
#'
#' @param indat the output from constdata = NULL, just a dummy variable.
#' @param hsargs a vector setting aspirational catches by SAU. They should sum 
#'     to the TAC
#' @param glb the globals object
#' @param projyear an index of the year for which the acatch are being estimated
#'     thus, if one has 29 years of data hen projyear would be 30.
#' @param outhcr a list of arrays generated by makehcrout within the HS package.
#'     It becomes the repository of all the HS scores and other outputs.
#' @param iter which iteration within reps is being run? Needed to output the
#'     scores to outhcr
#'
#' @return a list of the acatch and TAC
#' @export
#'
#' @examples
#' print("wait on data and time")
#' # indat=constdata; hsargs=hsargs;
consthcr <- function(indat,hsargs,glb,projyear=NULL,outhcr=outhcr,iter=iter) {
  acatch <- hsargs$acatch
  TAC <- sum(acatch,na.rm=TRUE)
  out <- list(acatch=acatch,TAC=TAC,multTAC=NULL,details=NULL,refpts=acatch)
  return(out)
} # end of consthcr



#' @title constdata processes the projections to produce the data for the HCR
#'
#' @description constdata takes the projection results from zoneDP, and histCE
#'     from 'otherdata', and appropriately samples them ready for the HCR
#'
#' @param tasCPUE a function that generates the CPUE statistics
#' @param tasFIS a function that generates the FIS statistics
#' @param tasNaS a function that generates the Numbers-at-size samples
#' @param sauCPUE the cpue by sau object from the dynamics object from the
#'     replicate model runs
#' @param sauacatch aspirational catches for each SAU from year-1
#' @param saucatch actual catches for each SAU from year-1, these are not needed
#'     in Tasmania or Victoria, but are needed (as well as acatch) in South
#'     Australia 
#' @param sauNAS the numbers-at-size data from the zoneDP object 
#' @param year the specific year being considered
#' @param decrement merely present to allow for HCR other than consthcr, hence
#'     set to NULL
#' @param startCE merely present to allow for HCR other than consthcr, hence
#'     set to NULL
#'
#' @return a list of arrce, yearnames, acatch, fis, and nas
#' @export
#'
#' @examples
#' print("wait on suitable data sets")
#' # constCPUE=sampleCE;constFIS=sampleFIS;constNAS=sampleNaS;sauCPUE=zoneDP$cesau;year=year;iter=iter;
#' # sauacatch=zoneDP$acatch
constdata <- function(tasCPUE,tasFIS, tasNaS, sauCPUE, sauacatch, saucatch,
                      sauNAS, year,decrement=NULL,startCE=NULL) {
  return(NULL)
} # end of constdata


#' @title makeouthcr creates an object to contain the replicate HCR outputs
#'
#' @description makeouthcr creates an objects required to hold the cumulative
#'     values for the grad4 pm. Otherwise the full run from 1992 - endyr must be
#'     recalculated each time. In this case it is a 3-D array
#'     set up to hold the values used on each SAUs previous years
#'     aspirational catch. Copies of the output array could also be used to
#'     store the scores developed for the different components of the HCR.
#'
#' @param glb the globals object for the MSE
#' @param hsargs the harvest strategy arguments, in this case a vector of
#'     aspirational catches for each sau
#'
#' @return in this case it merely returns the vector of catches in hsargs
#' @export
#'
#' @examples
#' makeoutconst(glb=NULL,hsargs=c(10,20,30,40,50,60,70,80))
makeoutconst <- function(glb,hsargs) { # glb=glb; hsargs=hsargs
  return(hsargs)
} # end of makeoutconst







